---
- name: Configure Docker Host systems
  hosts: docker_hosts

  vars_files:
    - vars/system_vars.yml

  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - "{{ username }}"
      tags: ['docker']
      become: true

  tasks:
    - name: Set up Ubuntu
      ansible.builtin.import_tasks: tasks/ubuntu/base/main.yml
      tags: ['base']

  handlers:
    - name: Restart SSH daemon
      ansible.builtin.service:
        name: sshd
        state: restarted
      become: true
