---
- name: Configure Docker Host systems
  hosts: docker_hosts

  vars_files:
    - vars/system_vars.yml
    - vars/docker_container_vars.yml
    - vars/secret_vars.yml

  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - "{{ username }}"
      tags: ['docker']
      become: true

  tasks:
    - name: Set up Ubuntu
      ansible.builtin.import_tasks: tasks/ubuntu/base/main.yml
      tags: ['base']
    - name: Configure Docker network
      ansible.builtin.import_tasks: tasks/docker-containers/docker-network.yml
      tags: ['docker_network']
    - name: Deploy Portainer Container
      ansible.builtin.import_tasks: tasks/docker-containers/portainer/main.yml
      tags: ['never', 'portainer']
    - name: Set up Portainer Agent
      ansible.builtin.import_tasks: tasks/docker-containers/portainer/agent.yml
      tags: ['never', 'portainer_agent']

  handlers:
    - name: Restart SSH daemon
      ansible.builtin.service:
        name: sshd
        state: restarted
      become: true
