---
- name: Update Home servers
  hosts: servers

  vars_files:
    - vars/system_vars.yml

  tasks:
    - name: Configure Homepage
      ansible.builtin.import_tasks: tasks/docker-containers/homepage/main.yml
      tags: ['homepage']
