---
- name: Deploy Portainer container.
  community.docker.docker_container:
    name: Portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portatiner_data:/data
    network_mode: bridge
    restart_policy: always
