---
- name: Copy arr_backup.sh over to host
  ansible.builtin.template:
    src: templates/arr_backup.sh.j2
    dest: "{{ backup_scripts_path }}/arr_backup.sh"
    owner: root
    group: docker
    mode: 'u=rwx,g=rx,o=rx'

- name: Check gdrive exists
  ansible.builtin.stat:
    path: /usr/bin/gdrive
  register: gdrive_stat

- name: Download gdrive 3
  ansible.builtin.get_url:
    url: "https://github.com/glotlabs/gdrive/releases/download/{{ gdrive_version }}/gdrive_linux-x64.tar.gz"
    dest: /tmp/gdrive_linux-x64.tar.gz
    mode: '0755'
  when: not gdrive_stat.stat.exists

- name: Extract /tmp/gdrive_linux-x64.tar.gz into /usr/local/gdrive
  ansible.builtin.unarchive:
    src: /tmp/gdrive_linux-x64.tar.gz
    dest: /usr/local/gdrive
  when: not gdrive_stat.stat.exists

- name: User message
  ansible.builtin.debug:
    msg: "You now need to run: gdrive account add"
  when: not gdrive_stat.stat.exists

- name: Set cron for backup
  ansible.builtin.cron:
    name: "arr_backup"
    minute: "3"
    hour: "0"
    job: "/bin/bash {{ backup_scripts_path }}/arr_backup.sh > /dev/null 2>&1"
