---
- name: Create the homepage config directory.
  ansible.builtin.file:
    path: "{{ homepage_config_path }}"
    state: directory
    mode: '0755'

- name: Deploy homepage Docker container.
  community.docker.docker_container:
    name: Homepage
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - "3000:3000"
    volumes:
      - "{{ homepage_config_path }}:/app/config" # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    env:
      PUID: '1000'
      PGID: '1000'
    network_mode: "{{ docker_network }}"
    restart_policy: unless-stopped

- name: Copy Homepage settings configuration file
  ansible.builtin.template:
    src: templates/settings.yaml.j2
    dest: "{{ homepage_config_path }}/settings.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u=rw,g=rw,o=r

- name: Copy Homepage widgets configuration file
  ansible.builtin.template:
    src: templates/widgets.yaml.j2
    dest: "{{ homepage_config_path }}/widgets.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u=rw,g=rw,o=r

- name: Copy Homepage service configuration file
  ansible.builtin.template:
    src: templates/services.yaml.j2
    dest: "{{ homepage_config_path }}/services.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u=rw,g=rw,o=r
