---
- name: Create Media directories.
  ansible.builtin.file:
    path: "{{ media_dir }}"
    state: directory
    mode: '0755'

- name: Create the Jellyfin config directory.
  ansible.builtin.file:
    path: "{{ jellyfin_path }}/config"
    state: directory
    mode: '0755'

- name: Create the Jellyfin cache directory.
  ansible.builtin.file:
    path: "{{ jellyfin_path }}/cache"
    state: directory
    mode: '0755'

- name: Deploy Jellyfin Docker container.
  community.docker.docker_container:
    name: Jellyfin
    image: jellyfin/jellyfin
    user: 1000:1000
    network_mode: host
    volumes:
      - "{{ media_dir }}:/media"
      - "{{ jellyfin_path }}/config:/config"
      - "{{ jellyfin_path }}/cache:/cache"
    restart_policy: unless-stopped
